package org.strand.authoring

import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import org.strand.core.Hash
import org.strand.core.JsonIngest
import org.strand.hashing.Hasher

/**
 * Q-063 — the bundled prelude module snapshot, loaded once per JVM.
 *
 * The snapshot is the dag-json document [PreludeModuleGenerator] produced
 * from the reserved-spec table, committed as a classpath resource so the
 * prelude exists as a verifiable, content-addressed artifact rather than a
 * per-program synthesis convention. Loading ingests and finalizes the
 * document, so every reserved name resolves to its content hash:
 *
 *  * manifest exports (the ForeignNode entries) resolve **through the
 *    manifest** — displayName → export target → content hash;
 *  * the remaining reserved nodes (types, effect categories) resolve through
 *    the snapshot's author-id table — they are the exports' dependencies and
 *    are pinned in `corpus/prelude-manifest.json` alongside the exports.
 *
 * [DagJsonEmitter] resolves reserved names against [nodeJson] instead of
 * re-synthesizing them per program; because the snapshot was generated by
 * the same JSON-shaping code the legacy synthesis path used (and
 * `PreludeModuleConformanceTest` pins the hashes), the resolved nodes are
 * byte-identical to the synthesized ones and no program hash changes.
 *
 * The CLI's default name registry is derived from [manifestHash] and
 * [nodeHashes], so `strand registry resolve fsWrite` answers from a clean
 * checkout with no registry file.
 */
object PreludeModule {

    /** Classpath location of the bundled snapshot. */
    const val RESOURCE_PATH = "/org/strand/authoring/prelude-module.json"

    /** The default registry name bound to the manifest hash. */
    const val REGISTRY_NAME = "prelude"

    /**
     * The loaded snapshot. Thrown [IllegalStateException] if the bundled
     * resource is missing or does not contain the manifest — both mean the
     * snapshot must be regenerated (see [PreludeModuleGenerator]).
     */
    data class Loaded(
        /** The snapshot document text, exactly as bundled. */
        val text: String,
        /** Content hash of the ModuleManifest root. */
        val manifestHash: Hash,
        /** Manifest exports: displayName → export target's content hash. */
        val exportHashes: Map<String, Hash>,
        /** Every reserved name → content hash (exports included). */
        val nodeHashes: Map<String, Hash>,
        /** Every reserved name → its dag-json node object (manifest excluded). */
        val nodesJson: Map<String, JsonObject>,
    )

    val loaded: Loaded by lazy { load() }

    /**
     * Resolve a reserved name to its admitted node's dag-json object. A miss
     * for a name the reserved-spec table knows means the bundled snapshot is
     * stale; the error says how to regenerate.
     */
    fun nodeJson(reservedId: String): JsonObject =
        loaded.nodesJson[reservedId] ?: throw IllegalStateException(
            "Reserved name '$reservedId' is not in the bundled prelude module snapshot " +
                "($RESOURCE_PATH) — the snapshot is stale relative to " +
                "LayerAGrammar.reservedNodes. Regenerate it from impl-kotlin/: " +
                REGENERATE_COMMAND
        )

    const val REGENERATE_COMMAND: String =
        ".\\gradlew.bat :corpus:test --tests \"org.strand.corpus.PreludeModuleConformanceTest\" " +
            "-Dstrand.regeneratePreludeModule=true"

    private fun load(): Loaded {
        val text = PreludeModule::class.java.getResourceAsStream(RESOURCE_PATH)
            ?.bufferedReader(Charsets.UTF_8)?.readText()
            ?: throw IllegalStateException(
                "Bundled prelude module snapshot missing at classpath $RESOURCE_PATH. " +
                    "Regenerate it from impl-kotlin/: $REGENERATE_COMMAND"
            )
        val document = Json.parseToJsonElement(text).jsonObject
        val nodesObj = document["nodes"]?.jsonObject
            ?: throw IllegalStateException("Prelude module snapshot has no 'nodes' object")
        val manifestObj = nodesObj[PreludeModuleGenerator.MANIFEST_AUTHOR_ID]?.jsonObject
            ?: throw IllegalStateException(
                "Prelude module snapshot has no '${PreludeModuleGenerator.MANIFEST_AUTHOR_ID}' " +
                    "ModuleManifest node — regenerate it: $REGENERATE_COMMAND"
            )

        val ingest = JsonIngest.parse(text)
        val hasher = Hasher(ingest.rawStore)
        val finalized = hasher.finalize(ingest.root)
        val manifestHash = finalized.nodeIdToHash.getValue(finalized.root)

        fun hashOf(authorId: String): Hash {
            val nodeId = ingest.nameMap[authorId]
                ?: throw IllegalStateException("Prelude snapshot references unknown author id '$authorId'")
            // Nodes no manifest export references (StateMachine effect
            // categories, the ErrorPayload type trio) are hashed standalone —
            // the canonical encoding is context-independent (see
            // PreludeModuleGenerator.generate).
            return finalized.nodeIdToHash[nodeId]
                ?: hasher.hashReachable(nodeId)[nodeId]
                ?: throw IllegalStateException("Prelude snapshot node '$authorId' has no content hash")
        }

        // Exports resolve through the manifest: displayName → target → hash.
        val exportHashes = manifestObj["exports"]!!.jsonArray.associate { export ->
            val obj = export.jsonObject
            val displayName = obj["displayName"]!!.jsonPrimitive.content
            val target = obj["target"]!!.jsonPrimitive.content
            displayName to hashOf(target)
        }
        val nodeNames = nodesObj.keys.filter { it != PreludeModuleGenerator.MANIFEST_AUTHOR_ID }
        val nodeHashes = nodeNames.associateWith { hashOf(it) }
        val nodesJson = nodeNames.associateWith { nodesObj.getValue(it).jsonObject }

        return Loaded(
            text = text,
            manifestHash = manifestHash,
            exportHashes = exportHashes,
            nodeHashes = nodeHashes,
            nodesJson = nodesJson,
        )
    }
}
